# This file was generated by GoReleaser. DO NOT EDIT.
cask "radosgw-assume" do
  version "2.0.0"

  on_macos do
    on_intel do
      sha256 "e5fde516db2474ebeec777da66f7384582e865e0567bd3afbc6f016e4fd06c78"
      url "https://github.com/fitbeard/radosgw-assume/releases/download/v#{version}/radosgw-assume-v#{version}-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "5c594c60dd85fd544d08c33f493660a5470a9f40041e5ea26e0d3a50268434bc"
      url "https://github.com/fitbeard/radosgw-assume/releases/download/v#{version}/radosgw-assume-v#{version}-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "41be5616fb60917f2dd842950892d07790093a19b1e136a8c6cf4b3adf44e67c"
      url "https://github.com/fitbeard/radosgw-assume/releases/download/v#{version}/radosgw-assume-v#{version}-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "76b7d5b701ae7bb386a216f250cd7c452ba506f3421dba225ad2324eadb6fe7f"
      url "https://github.com/fitbeard/radosgw-assume/releases/download/v#{version}/radosgw-assume-v#{version}-linux-arm64.tar.gz"
    end
  end

  name "radosgw-assume"
  desc "CLI tool for AWS STS role assumption with RadosGW."
  homepage "https://github.com/fitbeard/radosgw-assume"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "radosgw-assume"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/radosgw-assume"]
    end
  end

  # No zap stanza required

end
