# This file was generated by GoReleaser. DO NOT EDIT.
cask "radosgw-assume" do
  version "1.4.4"

  on_macos do
    on_intel do
      sha256 "63156b9b0b412277353671a448f92a5530e265ec7598acfafd11a047b1eaf18d"
      url "https://github.com/fitbeard/radosgw-assume/releases/download/v#{version}/radosgw-assume-v#{version}-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "be72aa48bba2b005316fd2a2a66a163459d565fa19c5802e146fb9fa5eab126b"
      url "https://github.com/fitbeard/radosgw-assume/releases/download/v#{version}/radosgw-assume-v#{version}-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ef64223c34b56fac9ea2ccc9a1219dcfe5d9548809f0f19b6096148a581f0db4"
      url "https://github.com/fitbeard/radosgw-assume/releases/download/v#{version}/radosgw-assume-v#{version}-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "fd0b3377eeaa2f2fa07143903726c3606d707ca045f9fe07d82eea4ab68d3de5"
      url "https://github.com/fitbeard/radosgw-assume/releases/download/v#{version}/radosgw-assume-v#{version}-linux-arm64.tar.gz"
    end
  end

  name "radosgw-assume"
  desc "CLI tool for AWS STS role assumption with RadosGW."
  homepage "https://github.com/fitbeard/radosgw-assume"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "radosgw-assume"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/radosgw-assume"]
    end
  end

  # No zap stanza required

end
