# This file was generated by GoReleaser. DO NOT EDIT.
cask "radosgw-assume" do
  version "1.4.2"

  on_macos do
    on_intel do
      sha256 "95414311448bf4703460793ffa1b83b0b9e14e9f4a69a839e1b18cd2cbf9b35a"
      url "https://github.com/fitbeard/radosgw-assume/releases/download/v#{version}/radosgw-assume-v#{version}-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "15b42ed771caad51af4a325db5100416f6ca5bf87f7e7fe84c63fac7d30ccc6e"
      url "https://github.com/fitbeard/radosgw-assume/releases/download/v#{version}/radosgw-assume-v#{version}-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "71a8ba29523cbb50450bb093eb2f920f94ab0e1a3b6fe925e316d5f462a4a5cb"
      url "https://github.com/fitbeard/radosgw-assume/releases/download/v#{version}/radosgw-assume-v#{version}-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "f3fab45d073d15d26c50cfb78d0cb723ad7fa1aba5a19a456f80df3f4e2521e8"
      url "https://github.com/fitbeard/radosgw-assume/releases/download/v#{version}/radosgw-assume-v#{version}-linux-arm64.tar.gz"
    end
  end

  name "radosgw-assume"
  desc "CLI tool for AWS STS role assumption with RadosGW."
  homepage "https://github.com/fitbeard/radosgw-assume"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "radosgw-assume"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/radosgw-assume"]
    end
  end

  # No zap stanza required

end
