# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RadosgwAssume < Formula
  desc "CLI tool for AWS STS role assumption with RadosGW."
  homepage "https://github.com/fitbeard/radosgw-assume"
  version "1.3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fitbeard/radosgw-assume/releases/download/v1.3.0/radosgw-assume-v1.3.0-darwin-amd64.tar.gz"
      sha256 "262598f158c192ed51b06fda506b26b21f46feec37ab144aec424861326460ca"

      def install
        bin.install "radosgw-assume"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fitbeard/radosgw-assume/releases/download/v1.3.0/radosgw-assume-v1.3.0-darwin-arm64.tar.gz"
      sha256 "f54445aff50552bed0094236ac9bf9c64737af75437af430011d69828ddcb24c"

      def install
        bin.install "radosgw-assume"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fitbeard/radosgw-assume/releases/download/v1.3.0/radosgw-assume-v1.3.0-linux-amd64.tar.gz"
      sha256 "635172ed40b83940e9f13d70ef5559837af9ac6b04b246c545243898f6c9dba7"
      def install
        bin.install "radosgw-assume"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fitbeard/radosgw-assume/releases/download/v1.3.0/radosgw-assume-v1.3.0-linux-arm64.tar.gz"
      sha256 "1d40afe47acf4216991a6af63b6df388bd041e2a67c03ff8998496e3d6e36a4d"
      def install
        bin.install "radosgw-assume"
      end
    end
  end

  test do
    system "radosgw-assume version"
  end
end
